### PR TITLE
add gitter channel to README.md

### LINKED ISSUE #4: Improve README.md
**I'm submitting a ...**
- [x] feature request

Improve our README file.

**Steps to reproduce:**
you may mention our gitter channel link https://gitter.im/Addy-Smart-Addresses

### PR DESCRIPTION
**Pull request by davidbru**
Fixes #4

### CODE REVIEW

**Comment by yashovardhanagrawal** [comment]
Thanks for the PR.
Let others review it first then we will be ready to merge it!

**Comment by davidbru** [comment]
You are welcome

**Comment by ihsraham** [comment]
@yashovardhanagrawal It's ready to be merged.

**Comment by yashovardhanagrawal** [comment]
All right!
lets merge it then

**Pull request merged**
