### PR TITLE
update README.md

### LINKED ISSUE #39: Update README.md
### Overview Description

Contributing guideline URL in README.md direct to README.md. Change the URL so it opens CONTRIBUTING.md file.

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixed #39

### CODE REVIEW

**Review by yashovardhan — CHANGES_REQUESTED** [review]
the changes seem fine

can you change your commit message to `README.md: Fix link for Guidelines`?

**Comment by liveHarshit** [comment]
Commit updated.

**Comment by liveHarshit** [comment]
Closing

**Comment by yashovardhanagrawal** [comment]
LGTM

**Pull request merged**
